# Dataset and Splits
data_root: DATA
dataset_class: datasets.node_prediction.CitiBikeDatasetInterface
dataset_name: citibike
data_splits_file: DATA_SPLITS/citibike/citibike_outer1_inner5.splits

# Hardware
device: cpu
max_cpus: 1
max_gpus: 0
gpus_per_task: 0

# Data Loading
dataset_getter: pydgn.data.provider.SingleGraphSequenceDataProvider
data_loader:
  class_name: torch.utils.data.DataLoader
  args:
    num_workers: 0
    pin_memory: False

# Reproducibility
seed: 42

# Experiment
result_folder: RESULTS
exp_name: citibike_gcrn_lstm
experiment: pydgn.experiment.supervised_task.SupervisedTask
higher_results_are_better: False
evaluate_every: 1
final_training_runs: 5

# Temporal info
reset_eval_model_hidden_state: False

grid:
  supervised_config:
    model: models.spatio_temporal_model.GCRN_LSTM_Model
    checkpoint: True
    shuffle: False
    batch_size: 32
    epochs: 1000

    # Model specific arguments #
    dim_embedding:
      - 8  # best hyper-param
      - 4
      - 2
      - 1  # This is the input dim
    K:
      - 1
      - 2
      - 3  # best hyper-param
    normalization:
      - null
      - sym  # best hyper-param
      - rw

    optimizer:
      - class_name: pydgn.training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.AdamW
          lr:
            - 0.01
            - 0.001  # best hyper-param
            - 0.0001
          weight_decay: 
            - 0.001  # best hyper-param
            - 0.0001

    # Scheduler (optional)
    scheduler: null

    # Loss metric
    loss:
      - pydgn.training.callback.metric.MeanAverageError

    # Score metric
    scorer:
      - class_name: pydgn.training.callback.metric.MultiScore
        args:
          main_scorer: pydgn.training.callback.metric.MeanAverageError
          my_second_metric: pydgn.training.callback.metric.MeanSquareError

    # Readout (optional)
    readout: pydgn.model.readout.node_readout.LinearNodeReadout

    # Training engine
    engine:
      - class_name: pydgn.training.engine.GraphSequenceTrainingEngine
        args:
          engine_callback: pydgn.training.callback.engine_callback.TemporalEngineCallback

    # Gradient clipper (optional)
    gradient_clipper: null

    # Early stopper (optional)
    early_stopper:
      - class_name:
          - pydgn.training.callback.early_stopping.PatienceEarlyStopper
        args:
          patience:
            - 50
          monitor: validation_main_score
          mode: min  
          checkpoint: True

    # Plotter of metrics
    plotter: pydgn.training.callback.plotter.Plotter
